const data = {
	"SUBJECTS": [
		"angel",
		"fallen angel",
		"archangel",
		"seraph",
		"cherub",
		"demon",
		"demon lord",
		"succubus",
		"incubus",
		"devil",
		"hell knight",
		"abyss creature",
		"witch",
		"warlock",
		"sorcerer",
		"sorceress",
		"mage",
		"archmage",
		"battle mage",
		"illusionist",
		"necromancer",
		"druid",
		"elemental shaman",
		"healer",
		"alchemist",
		"oracle",
		"seer",
		"prophet",
		"mystic",
		"warrior",
		"barbarian",
		"knight",
		"paladin",
		"dragon slayer",
		"viking",
		"samurai",
		"ninja",
		"ronin",
		"assassin",
		"spy",
		"thief",
		"rogue",
		"ranger",
		"hunter",
		"mercenary",
		"gladiator",
		"archer",
		"duelist",
		"berserker",
		"valkyrie",
		"pirate",
		"pirate captain",
		"sea witch",
		"navigator",
		"corsair",
		"swashbuckler",
		"king",
		"queen",
		"emperor",
		"empress",
		"prince",
		"princess",
		"duke",
		"duchess",
		"noble",
		"royal consort",
		"goddess",
		"god",
		"demigod",
		"primordial deity",
		"Zeus",
		"Hera",
		"Athena",
		"Aphrodite",
		"Hermes",
		"Ares",
		"Poseidon",
		"Hades",
		"Artemis",
		"Demeter",
		"Dionysus",
		"Odin",
		"Thor",
		"Loki",
		"Freyja",
		"Tyr",
		"Hel",
		"Fenrir",
		"Ra",
		"Isis",
		"Anubis",
		"Horus",
		"Set",
		"Bastet",
		"cthulhu",
		"eldritch god",
		"cosmic horror entity",
		"void creature",
		"outer god",
		"ancient titan",
		"dragon",
		"wyvern",
		"hydra",
		"basilisk",
		"chimera",
		"griffin",
		"phoenix",
		"unicorn",
		"pegasus",
		"kraken",
		"leviathan",
		"gargoyle",
		"manticore",
		"harpy",
		"minotaur",
		"sphinx",
		"centaur",
		"faun",
		"satyr",
		"mermaid",
		"merman",
		"sea serpent",
		"giant",
		"troll",
		"ogre",
		"yeti",
		"werewolf",
		"vampire",
		"ghoul",
		"zombie",
		"revenant",
		"ghost",
		"spirit",
		"wraith",
		"shade",
		"djinn",
		"genie",
		"fairy",
		"pixie",
		"nymph",
		"dryad",
		"forest spirit",
		"elemental",
		"lava elemental",
		"ice elemental",
		"storm elemental",
		"shadow elemental",
		"light elemental",
		"robot",
		"android",
		"cyborg",
		"AI avatar",
		"mech pilot",
		"mech warrior",
		"exosuit soldier",
		"synthetic human",
		"gynoid",
		"nanobot swarm entity",
		"alien",
		"extraterrestrial",
		"gray alien",
		"reptilian alien",
		"cosmic traveler",
		"space marine",
		"starship captain",
		"astronaut",
		"space pirate",
		"galactic smuggler",
		"intergalactic bounty hunter",
		"cosmic sorcerer",
		"void wanderer",
		"nebula spirit",
		"superhero",
		"supervillain",
		"masked vigilante",
		"mutant",
		"shapeshifter",
		"time traveler",
		"dimension hopper",
		"chronomancer",
		"detective",
		"noir detective",
		"private investigator",
		"secret agent",
		"double agent",
		"spymaster",
		"scientist",
		"mad scientist",
		"inventor",
		"engineer",
		"mechanic",
		"pilot",
		"fighter pilot",
		"sailor",
		"captain",
		"navigator",
		"chef",
		"artist",
		"musician",
		"ballet dancer",
		"fashion model",
		"photographer",
		"writer",
		"journalist",
		"philosopher",
		"scholar",
		"teacher",
		"doctor",
		"nurse",
		"surgeon",
		"monk",
		"priest",
		"nun",
		"shaman",
		"witch doctor",
		"athlete",
		"martial artist",
		"boxer",
		"wrestler",
		"gymnast",
		"swimmer",
		"runner",
		"archer",
		"swordsman",
		"sniper",
		"giant spider",
		"giant serpent",
		"giant eagle",
		"lion",
		"white lion",
		"tiger",
		"wolf",
		"bear",
		"owl",
		"hawk",
		"fox",
		"serpent",
		"raven",
		"stag",
		"golem",
		"stone golem",
		"crystal golem",
		"ice golem",
		"metal golem",
		"forest golem",
		"holy knight",
		"dark knight",
		"blood knight",
		"shadow priest",
		"sun priestess",
		"moon priestess",
		"star priestess",
		"cosmic witch",
		"storm witch",
		"forest guardian",
		"mountain guardian",
		"river spirit",
		"sky spirit",
		"sun spirit",
		"moon spirit",
		"anthropomorphic fox",
		"anthropomorphic wolf",
		"anthropomorphic dragon",
		"fashion influencer",
		"ceo",
		"business leader",
		"entrepreneur",
		"inventor",
		"visionary",
		"hero",
		"villain",
		"antihero",
		"legendary warrior",
		"chosen one",
		"prophecy child",
		"lost heir",
		"wanderer",
		"wayfarer",
		"traveler",
		"adventurer",
		"treasure hunter",
		"dungeon explorer"
	],
	"FEMALE SUBJECTS": [
		"woman",
		"young woman",
		"mysterious woman",
		"warrior woman",
		"beautiful woman",
		"elegant woman",
		"femme fatale",
		"dark seductress",
		"gothic beauty",
		"ethereal woman",
		"otherworldly woman",
		"cosmic woman",
		"queen",
		"empress",
		"princess",
		"duchess",
		"royal consort",
		"fallen queen",
		"phantom queen",
		"ice queen",
		"sun queen",
		"moon queen",
		"star queen",
		"underworld queen",
		"goddess",
		"ancient goddess",
		"forgotten goddess",
		"primordial goddess",
		"cosmic goddess",
		"storm goddess",
		"war goddess",
		"love goddess",
		"chaos goddess",
		"death goddess",
		"moon goddess",
		"sun goddess",
		"forest goddess",
		"sea goddess",
		"serpent goddess",
		"Athena",
		"Artemis",
		"Aphrodite",
		"Demeter",
		"Hera",
		"Persephone",
		"Hecate",
		"Freyja",
		"Hel",
		"Isis",
		"Bastet",
		"Nephthys",
		"Amaterasu",
		"angel",
		"seraphim woman",
		"fallen angel woman",
		"celestial maiden",
		"light angel",
		"dark angel",
		"angelic warrior",
		"angelic healer",
		"angelic messenger",
		"demoness",
		"demonic temptress",
		"hell queen",
		"succubus",
		"abyssal witch",
		"shadow demoness",
		"void demoness",
		"hellfire maiden",
		"witch",
		"shadow witch",
		"forest witch",
		"sea witch",
		"bone witch",
		"blood witch",
		"storm witch",
		"crystal witch",
		"moon witch",
		"sun witch",
		"cosmic witch",
		"necromancer woman",
		"occult priestess",
		"ritual sorceress",
		"sorceress",
		"archmage woman",
		"battle mage woman",
		"illusionist woman",
		"elemental priestess",
		"shamaness",
		"oracle woman",
		"seer woman",
		"prophetess",
		"spirit medium",
		"astral traveler",
		"dreamwalker",
		"valkyrie",
		"shieldmaiden",
		"viking warrior woman",
		"samurai woman",
		"ninja woman",
		"ronin woman",
		"assassin woman",
		"spy woman",
		"deadly infiltrator",
		"rogue woman",
		"ranger woman",
		"archer woman",
		"bounty huntress",
		"warrior woman",
		"barbarian woman",
		"gladiator woman",
		"berserker woman",
		"swordmaster woman",
		"duelist woman",
		"pirate woman",
		"pirate captain woman",
		"sea raider woman",
		"corsair woman",
		"mermaid",
		"mermaid queen",
		"siren",
		"siren temptress",
		"siren songstress",
		"sea nymph",
		"ocean spirit woman",
		"fairy woman",
		"high fairy queen",
		"dark fairy",
		"forest nymph woman",
		"dryad woman",
		"blossom spirit woman",
		"flower maiden",
		"moth fairy",
		"sun sprite woman",
		"moon sprite woman",
		"phoenix maiden",
		"fire spirit woman",
		"storm spirit woman",
		"light spirit woman",
		"shadow spirit woman",
		"dragon maiden",
		"dragon rider woman",
		"dragon priestess",
		"draconic enchantress",
		"harpy woman",
		"lamia",
		"medusa",
		"gorgon woman",
		"sphinx woman",
		"manticore woman",
		"centaur woman",
		"minotaur woman (feminine)",
		"satyr woman",
		"chimera woman",
		"ghost woman",
		"phantom lady",
		"wailing spirit woman",
		"haunted maiden",
		"revenant woman",
		"wraith woman",
		"shadow woman",
		"ink shadow maiden",
		"vampire woman",
		"vampire queen",
		"blood priestess",
		"dhampir woman",
		"nightwalker woman",
		"werewolf woman",
		"wolf maiden",
		"she-beast",
		"huntress of the moon",
		"gargoyle woman",
		"stone maiden",
		"crystal sentinel woman",
		"obsidian guardian woman",
		"elemental woman",
		"fire elemental woman",
		"water elemental woman",
		"air elemental woman",
		"earth elemental woman",
		"lightning elemental woman",
		"ice elemental woman",
		"cosmic elemental woman",
		"android woman",
		"gynoid",
		"synthetic woman",
		"cybernetic woman",
		"cyborg woman",
		"robotic maiden",
		"AI avatar woman",
		"hologram woman",
		"virtual reality woman",
		"glitch spirit woman",
		"nanobot swarm woman (humanoid)",
		"space warrior woman",
		"space pirate woman",
		"space knight woman",
		"starship captain woman",
		"intergalactic traveler woman",
		"extraterrestrial woman",
		"alien queen",
		"void priestess",
		"cosmic wanderer woman",
		"time traveler woman",
		"chronomancer woman",
		"dimension-hopping woman",
		"multiverse wanderer woman",
		"superheroine",
		"masked heroine",
		"antiheroine",
		"vigilante woman",
		"shadow vigilante woman",
		"scientist woman",
		"mad scientist woman",
		"inventor woman",
		"engineer woman",
		"mechanic woman",
		"techno-witch woman",
		"tech mage woman",
		"cyberpunk hacker woman",
		"cyberpunk assassin woman",
		"neon street samurai woman",
		"detective woman",
		"noir detective woman",
		"private investigator woman",
		"secret agent woman",
		"double agent woman",
		"spy mistress",
		"doctor woman",
		"nurse woman",
		"surgeon woman",
		"healer woman",
		"artist woman",
		"musician woman",
		"ballet dancer woman",
		"dancer woman",
		"fashion model woman",
		"performer woman",
		"illusion dancer woman",
		"ritual dancer woman",
		"athlete woman",
		"martial artist woman",
		"gymnast woman",
		"swordswoman",
		"archer woman",
		"forest guardian woman",
		"mountain guardian woman",
		"river spirit woman",
		"sun priestess",
		"moon priestess",
		"star priestess",
		"gothic nun",
		"occult nun",
		"warrior nun",
		"underworld priestess",
		"spirit guide woman",
		"death priestess",
		"living statue woman",
		"porcelain doll woman",
		"clockwork doll woman",
		"marionette maiden",
		"crystal maiden",
		"glass spirit woman",
		"dream spirit woman",
		"nightmare woman",
		"sleep demoness",
		"reality-bending woman",
		"surreal woman",
		"cosmic surrealist woman",
		"fire goddess avatar",
		"ice empress",
		"storm empress",
		"shadow empress",
		"void empress",
		"cosmic empress",
		"ice dragon woman",
		"flame dragon woman",
		"light dragon woman",
		"shadow dragon woman",
		"kraken priestess",
		"leviathan maiden",
		"serpent priestess",
		"forest witch queen",
		"sea witch queen",
		"mountain witch queen",
		"desert witch queen",
		"cyber angel woman",
		"mechanical angel woman",
		"nanite goddess",
		"quantum sorceress",
		"succubus queen",
		"abyss queen",
		"void temptress",
		"frost giantess",
		"stone giantess",
		"cosmic giantess",
		"guardian angel woman",
		"guardian spirit woman",
		"sun avatar woman",
		"moon avatar woman",
		"star avatar woman",
		"cosmic avatar woman"
	],
	"CLOTHING": [
		"lace corset",
		"silk slip",
		"sheer bodysuit",
		"black lingerie set",
		"lace stockings",
		"garter belt",
		"fishnet tights",
		"choker harness",
		"lace bralette",
		"silk nightgown",
		"open back dress",
		"deep v dress",
		"cutout bodysuit",
		"sheer robe",
		"slitted gown",
		"tight pencil skirt",
		"pleated mini skirt",
		"ruffled mini dress",
		"off shoulder dress",
		"corset top",
		"mesh crop top",
		"halter top",
		"strapless dress",
		"backless gown",
		"ball gown",
		"evening gown",
		"wedding gown",
		"cocktail dress",
		"bodycon dress",
		"wrap dress",
		"a line skirt",
		"flowy maxi skirt",
		"pleated skirt",
		"ruffled skirt",
		"kimono robe",
		"silk kimono",
		"cheongsam dress",
		"hanfu gown",
		"yukata robe",
		"sari wrap",
		"abaya cloak",
		"kaftan gown",
		"poncho wrap",
		"trench coat",
		"fur coat",
		"shearling jacket",
		"leather jacket",
		"denim jacket",
		"bomber jacket",
		"cropped jacket",
		"motorcycle jacket",
		"blazer jacket",
		"military jacket",
		"tailcoat",
		"cape coat",
		"hooded cloak",
		"fashion cape",
		"feathered cape",
		"crystal cape",
		"dragon scale cape",
		"moonlight cloak",
		"shadow silk cloak",
		"phoenix feather cloak",
		"swimsuit",
		"bikini",
		"micro bikini",
		"string bikini",
		"retro swimsuit",
		"high waist bikini",
		"mermaid tail skirt",
		"armor corset",
		"elven armor",
		"dark knight armor",
		"crystal armor",
		"moonlight armor",
		"forest dryad armor",
		"angelic breastplate",
		"demonic breastplate",
		"dragonbone armor",
		"runic armor",
		"mage robe",
		"witch dress",
		"enchantress gown",
		"valkyrie armor",
		"succubus outfit",
		"battle bikini armor",
		"leather catsuit",
		"latex catsuit",
		"black bodysuit",
		"stealth suit",
		"futuristic suit",
		"sci fi exosuit",
		"pilot jumpsuit",
		"space suit",
		"crystal bodysuit",
		"hologram suit",
		"shadow suit",
		"neon armor suit",
		"crop sweater",
		"turtleneck sweater",
		"oversized sweater",
		"cardigan sweater",
		"hoodie sweatshirt",
		"zip hoodie",
		"sports bra",
		"yoga top",
		"athletic leggings",
		"yoga leggings",
		"running shorts",
		"gym shorts",
		"track pants",
		"sweatpants",
		"workout set",
		"school uniform",
		"pleated school skirt",
		"academy blazer",
		"gothic lolita dress",
		"maid outfit",
		"nurse outfit",
		"combat uniform",
		"steampunk corset",
		"victorian dress",
		"baroque gown",
		"renaissance bodice",
		"pirate blouse",
		"captain coat",
		"cowgirl outfit",
		"fur shawl",
		"feather boa",
		"silk scarf",
		"lace gloves",
		"opera gloves",
		"leather gloves",
		"arm wraps",
		"arm warmers",
		"fingerless gloves",
		"lace choker",
		"rhinestone choker",
		"pearl necklace",
		"gold necklace",
		"ankle boots",
		"thigh high boots",
		"combat boots",
		"high heels",
		"stiletto heels",
		"platform heels",
		"strappy heels",
		"lace up heels",
		"sun hat",
		"straw hat",
		"wide brim hat",
		"beret",
		"beanie",
		"hooded cowl",
		"witch hat",
		"crown",
		"tiara",
		"crystal tiara",
		"thorn crown",
		"halo crown",
		"feathered headpiece",
		"veil",
		"lace veil",
		"face mask",
		"silk mask",
		"crystal mask",
		"masquerade mask",
		"denim jeans",
		"skinny jeans",
		"ripped jeans",
		"leather pants",
		"high waist trousers",
		"tight leggings",
		"cargo pants",
		"silk trousers",
		"trench dress",
		"denim dress",
		"linen dress",
		"knit dress",
		"fur trimmed cloak",
		"crystal embroidered gown",
		"gold trimmed dress",
		"silver sequin dress",
		"pearl beaded dress",
		"diamond studded gown",
		"velvet gown",
		"satin dress",
		"chiffon dress",
		"angel wings harness",
		"demon wings harness",
		"feather wings",
		"crystal wings",
		"shadow wings",
		"serpent scale dress",
		"moonlight dress",
		"starlight gown",
		"nebula silk dress",
		"aurora dress",
		"sunfire gown",
		"rose petal dress",
		"lotus bloom dress",
		"thorn vine bodice",
		"living flower dress",
		"water silk gown",
		"liquid metal dress",
		"glass shard dress",
		"crystal prism suit",
		"shadow fabric gown",
		"hologram dress",
		"star map bodysuit",
		"galaxy print dress",
		"petal skirt",
		"butterfly wing dress",
		"feather skirt",
		"scales bodysuit",
		"ice crystal dress",
		"ember dress",
		"storm silk gown",
		"rainbow shimmer dress",
		"opal sheen dress",
		"mirage fabric veil",
		"magical girl outfit",
		"battle mage coat",
		"forest witch cloak",
		"desert nomad wraps",
		"ocean priestess robe",
		"lace up corset dress",
		"sheer embroidered top",
		"crystal mesh bodysuit",
		"silk harness top",
		"pearl encrusted lingerie",
		"illusion bodysuit",
		"lace cutout dress"
	],
	"CLOTHING STYLES": [
		"gothic couture",
		"dark elegance",
		"angelic couture",
		"ethereal fantasy",
		"high fashion editorial",
		"runway avant garde",
		"cyberpunk streetwear",
		"neon cyber couture",
		"post apocalyptic armor",
		"dystopian uniform",
		"sci fi tactical",
		"space opera regal",
		"futuristic minimalism",
		"techwear armor",
		"biomechanical fashion",
		"steampunk aristocrat",
		"clockwork couture",
		"dieselpunk uniform",
		"retro futurist fashion",
		"ancient warrior chic",
		"mythic goddess style",
		"elven royal style",
		"dark fae glamour",
		"forest witch aesthetic",
		"desert nomad style",
		"ocean priestess style",
		"arctic huntress gear",
		"valkyrie warrior chic",
		"succubus glamour",
		"vampiric elegance",
		"necromancer robes",
		"mage academy uniform",
		"battle mage couture",
		"ritual priestess attire",
		"moon priestess aesthetic",
		"sun priestess aesthetic",
		"stormborn couture",
		"shadow dancer style",
		"illusionist glam",
		"enchanted noble attire",
		"royal court fashion",
		"baroque elegance",
		"rococo fantasy",
		"victorian gothic",
		"edwardian couture",
		"renaissance noble dress",
		"medieval court style",
		"pirate queen fashion",
		"silk road attire",
		"nomadic silk fashion",
		"samurai inspired fashion",
		"geisha elegance",
		"warrior monk aesthetic",
		"belly dancer costume",
		"arabesque couture",
		"high priestess ceremonial",
		"ritualistic gown style",
		"crystal mage aesthetic",
		"starlight couture",
		"celestial elegance",
		"galactic fashion",
		"nebula royal style",
		"astral wanderer attire",
		"dreamlike surreal fashion",
		"liquid silhouette fashion",
		"bioluminescent couture",
		"organic growth fashion",
		"flower goddess style",
		"petal couture",
		"thorn queen style",
		"feathered celestial silhouette",
		"dragon queen armor style",
		"fairy tale couture",
		"vintage pinup style",
		"retro chic",
		"modern streetwear",
		"minimalist chic",
		"athleisure modernism",
		"luxury loungewear",
		"velvet boudoir aesthetic",
		"lace seduction style",
		"dark romance fashion",
		"romantic gothic",
		"witchcore fashion",
		"angelcore fashion",
		"demoncore fashion",
		"mermaid chic",
		"vampire aristocrat fashion",
		"crystal royalty aesthetic",
		"gothic couture",
		"dark elegance",
		"angelic couture",
		"ethereal fantasy",
		"high fashion editorial",
		"runway avant garde",
		"cyberpunk streetwear",
		"neon cyber couture",
		"post apocalyptic armor",
		"dystopian uniform",
		"sci fi tactical",
		"space opera regal",
		"futuristic minimalism",
		"techwear armor",
		"biomechanical fashion",
		"steampunk aristocrat",
		"clockwork couture",
		"dieselpunk uniform",
		"retro futurist fashion",
		"ancient warrior chic",
		"mythic goddess style",
		"elven royal style",
		"dark fae glamour",
		"forest witch aesthetic",
		"desert nomad style",
		"ocean priestess style",
		"arctic huntress gear",
		"valkyrie warrior chic",
		"succubus glamour",
		"vampiric elegance",
		"necromancer robes",
		"mage academy uniform",
		"battle mage couture",
		"ritual priestess attire",
		"moon priestess aesthetic",
		"sun priestess aesthetic",
		"stormborn couture",
		"shadow dancer style",
		"illusionist glam",
		"enchanted noble attire",
		"royal court fashion",
		"baroque elegance",
		"rococo fantasy",
		"victorian gothic",
		"edwardian couture",
		"renaissance noble dress",
		"medieval court style",
		"pirate queen fashion",
		"silk road attire",
		"nomadic silk fashion",
		"samurai inspired fashion",
		"geisha elegance",
		"warrior monk aesthetic",
		"belly dancer costume",
		"arabesque couture",
		"high priestess ceremonial",
		"ritualistic gown style",
		"crystal mage aesthetic",
		"starlight couture",
		"celestial elegance",
		"galactic fashion",
		"nebula royal style",
		"astral wanderer attire",
		"dreamlike surreal fashion",
		"liquid silhouette fashion",
		"bioluminescent couture",
		"organic growth fashion",
		"flower goddess style",
		"petal couture",
		"thorn queen style",
		"feathered celestial silhouette",
		"dragon queen armor style",
		"fairy tale couture",
		"vintage pinup style",
		"retro chic",
		"modern streetwear",
		"minimalist chic",
		"athleisure modernism",
		"luxury loungewear",
		"velvet boudoir aesthetic",
		"lace seduction style",
		"dark romance fashion",
		"romantic gothic",
		"witchcore fashion",
		"angelcore fashion",
		"demoncore fashion",
		"mermaid chic",
		"vampire aristocrat fashion",
		"crystal royalty aesthetic"
	],
	"PROPS": [
		"sword",
		"longsword",
		"katana",
		"greatsword",
		"rapier",
		"dagger",
		"throwing knife",
		"scimitar",
		"battle axe",
		"warhammer",
		"mace",
		"flail",
		"halberd",
		"spear",
		"trident",
		"bow",
		"crossbow",
		"shield",
		"tower shield",
		"buckler",
		"gauntlet weapon",
		"flaming sword",
		"ice blade",
		"void blade",
		"holy spear",
		"cursed dagger",
		"shadow scythe",
		"crystal staff",
		"arcane staff",
		"druidic staff",
		"necromancer staff",
		"thunder hammer",
		"phoenix bow",
		"dragonbone spear",
		"celestial orb",
		"enchanted mirror shield",
		"levitating grimoire",
		"runestone tablet",
		"potion vial",
		"magic cauldron",
		"summoning circle",
		"ritual dagger",
		"laser gun",
		"plasma rifle",
		"ion cannon",
		"energy sword",
		"gravity hammer",
		"railgun",
		"neon blade",
		"pulse pistol",
		"antimatter grenade",
		"nanobot injector",
		"quantum disruptor",
		"holographic shield",
		"teleport beacon",
		"camera",
		"film camera",
		"microphone",
		"tripod",
		"spotlight",
		"walkie-talkie",
		"drone",
		"tablet device",
		"smartphone",
		"VR headset",
		"headphones",
		"studio light",
		"police radio",
		"night-vision goggles",
		"grappling hook",
		"binoculars",
		"parachute pack",
		"combat knife",
		"tactical flashlight",
		"flare",
		"smoke bomb",
		"riot shield",
		"lockpick",
		"map",
		"compass",
		"survival kit",
		"mana crystal",
		"spirit lantern",
		"floating candles",
		"enchanted chain",
		"cursed book",
		"haunted doll",
		"witch’s broom",
		"crystal ball",
		"voodoo totem",
		"eldritch idol",
		"occult amulet",
		"bone mask",
		"ritual brazier",
		"blood-red rune stone",
		"levitating skull",
		"ghost lantern",
		"moonstone charm",
		"oracle mirror",
		"obsidian obelisk",
		"ancient sarcophagus",
		"otherworldly monolith",
		"portal frame",
		"golden crown",
		"ancient coin",
		"jeweled chalice",
		"golden idol",
		"royal scepter",
		"dragon egg",
		"treasure chest",
		"sun medallion",
		"crystal crown",
		"scroll of prophecy",
		"astral compass",
		"stone archway",
		"broken pillar",
		"cathedral window",
		"gothic door",
		"iron gate",
		"mansion staircase",
		"secret passage door",
		"cave crystals",
		"floating platform",
		"ritual altar",
		"teleportation gate",
		"Japanese torii gate",
		"floating runes",
		"stained-glass window",
		"glowing sigil on floor",
		"ancient throne",
		"obsidian throne",
		"tree stump throne",
		"sacrificial altar",
		"crystal pedestal",
		"void portal",
		"motorcycle",
		"bicycle",
		"vintage car",
		"sports car",
		"muscle car",
		"race car",
		"horse carriage",
		"hover bike",
		"hover car",
		"flying motorcycle",
		"jet plane",
		"fighter jet",
		"spaceship",
		"escape pod",
		"mech cockpit",
		"alien skiff",
		"sailboat",
		"rowboat",
		"submarine",
		"airship",
		"steampunk zeppelin",
		"dragon-drawn chariot",
		"hammer",
		"crowbar",
		"wrench",
		"pliers",
		"toolbox",
		"ladder",
		"stepladder",
		"rope coil",
		"anvil",
		"telescope",
		"magnifying glass",
		"lab microscope",
		"first aid kit",
		"fire extinguisher",
		"sewing kit",
		"paintbrush",
		"palette",
		"musical instrument",
		"violin",
		"guitar",
		"harp",
		"drum",
		"piano",
		"mirror",
		"broken mirror",
		"ornate mirror",
		"vanity table",
		"ancient bookcase",
		"floating bookshelf",
		"old desk",
		"writing quill",
		"ink bottle",
		"lantern",
		"torch",
		"candle holder",
		"hourglass",
		"grandfather clock",
		"music box",
		"treasure safe",
		"gilded frame",
		"marble statue",
		"broken statue",
		"crystal sculpture",
		"fountain",
		"birdcage",
		"server tower",
		"control panel",
		"hologram projector",
		"data crystal",
		"robotic arm",
		"security turret",
		"AI core",
		"neon sign",
		"energy coil",
		"fusion reactor",
		"quantum terminal",
		"cybernetic implant",
		"VR chair",
		"power generator",
		"synthetic heart",
		"nanotech console",
		"glowing cube",
		"floating sphere",
		"impossible staircase",
		"infinite hallway",
		"gravity-defying chair",
		"melting clock",
		"fractured mirror dimension shard",
		"void cube",
		"living painting",
		"door to nowhere",
		"floating key",
		"stairs made of light",
		"ladder of stars",
		"mirror that reflects a different world",
		"shadow creature silhouette",
		"light orb familiar",
		"cosmic egg",
		"vessel of memories",
		"astral string instrument",
		"lantern with a small galaxy inside",
		"runic gauntlet",
		"dragon skull helm",
		"spirit cage",
		"fae lantern",
		"druidic totem",
		"crown of thorns",
		"phoenix feather relic",
		"moon-blade shard",
		"starforged fragment",
		"robotic drone companion",
		"floating familiar",
		"mini dragon companion",
		"spirit wolf silhouette",
		"crystal golem core",
		"scroll with glowing runes",
		"book with moving ink",
		"holographic map",
		"floating geometric shapes",
		"ancient chained tome",
		"black cube monolith",
		"glass orb containing lightning",
		"summoner circle with candles",
		"energy vortex sphere",
		"fractured stone tablet",
		"cursed sword in stone",
		"bottle containing a storm",
		"lantern with trapped fire",
		"jar of glowing mist",
		"ice crystal shard",
		"fire crystal",
		"storm orb",
		"wind chime made of bones",
		"rainbow prism stone",
		"astronaut helmet",
		"samurai mask",
		"oni mask",
		"steampunk goggles",
		"arcane compass",
		"pocket watch with moving constellations",
		"enchanted rope",
		"ethereal chains",
		"floating crystal dagger",
		"cosmic hourglass",
		"mirror mask",
		"ghost sheet",
		"portal key",
		"archaic lockbox",
		"dimensional rift shard"
	],
	"POSES": [
		"standing tall",
		"standing relaxed",
		"standing with crossed arms",
		"standing with hands on hips",
		"standing with weight on one leg",
		"standing contrapposto",
		"leaning on a wall",
		"leaning forward",
		"leaning back casually",
		"leaning with arms crossed",
		"leaning on a railing",
		"posing with one hand on hip",
		"posing with both hands behind back",
		"posing with arms raised",
		"posing with hands clasped",
		"head tilted slightly",
		"gaze over the shoulder",
		"walking confidently",
		"walking slowly",
		"walking toward the viewer",
		"walking away dramatically",
		"mid step motion",
		"striding forward",
		"running lightly",
		"running full sprint",
		"charging forward",
		"spinning gracefully",
		"twirling dress",
		"dynamic turning pose",
		"hair flipping motion",
		"sitting casually",
		"sitting cross-legged",
		"sitting on edge of chair",
		"sitting on steps",
		"sitting on knees",
		"sitting with legs to the side",
		"lounging on couch",
		"reclining elegantly",
		"reclining like a queen",
		"lying on stomach with feet up",
		"lying on side gracefully",
		"lying on back with arms extended",
		"half-reclined seductive pose",
		"hands clasped together",
		"hands touching face",
		"hands running through hair",
		"hands behind head",
		"hands behind back",
		"hand reaching forward",
		"hand reaching upward",
		"one arm extended outward",
		"one hand covering mouth playfully",
		"hands forming a heart shape",
		"fashion runway walk",
		"glamour pose",
		"hip popped confidently",
		"arched back glamour pose",
		"head tilted fashion pose",
		"over the shoulder smirk",
		"arm draped elegantly",
		"hand on collar pose",
		"coat over shoulders pose",
		"seductive sideways glance",
		"long leg extension",
		"supermodel power stance",
		"wind blowing hair pose",
		"bashful pose",
		"shy head tilt",
		"cute peace sign pose",
		"playfully covering face",
		"playful wink pose",
		"hands clasped cutely",
		"innocent upward gaze",
		"soft gentle smile pose",
		"kneeling cutely",
		"jumping lightly in joy",
		"battle ready stance",
		"combat crouch",
		"superhero landing",
		"superhero power stance",
		"archer aiming pose",
		"sword raised overhead",
		"sword pointing forward",
		"magical casting pose",
		"charging with weapon",
		"dual wield stance",
		"martial arts kick",
		"martial arts punch",
		"mid air leap",
		"acrobat flip motion",
		"landing from a jump",
		"telekinetic power pose",
		"energy summoning pose",
		"spell throwing pose",
		"force push gesture",
		"reaching out longingly",
		"holding chest emotionally",
		"kneeling in sorrow",
		"hands trembling pose",
		"looking upward in hope",
		"gaze lowered in sadness",
		"eyes closed serene pose",
		"desperate reaching pose",
		"praying pose",
		"whispering to someone unseen",
		"levitating gently",
		"levitating in meditation",
		"floating in fetal position",
		"ascending into light",
		"falling through void",
		"gravity defying arch pose",
		"arms extended like wings",
		"mirror reflection pose",
		"shadow self confrontation pose",
		"floating upside down",
		"hovering above ground",
		"glowing aura summoning pose",
		"calling celestial light pose",
		"possessed twisted pose",
		"halo manifestation pose",
		"standing atop ruins",
		"raising a flag",
		"wielding a giant weapon",
		"lifting something heavy",
		"arms spread wide heroic",
		"shouting in battle",
		"kingdom protector stance",
		"guardian sentinel posture",
		"hands glowing with energy",
		"epic pointing gesture",
		"crouched predator pose",
		"crawling slowly",
		"emerging from shadows",
		"head lowered sinister",
		"arms dangling lifelessly",
		"screaming silently pose",
		"ghostly reaching pose",
		"broken doll pose",
		"ritualistic kneeling pose",
		"contorted supernatural pose",
		"hand tracing neckline",
		"arching back sensually",
		"hip sway posture",
		"slow hair sweep",
		"legs crossed elegantly",
		"lying on silk sheets",
		"seductive lean forward",
		"lingering touch on lips",
		"silhouette tease pose",
		"channeling fire pose",
		"channeling water pose",
		"channeling lightning pose",
		"channeling earth pose",
		"wind swirling around pose",
		"rising from mist",
		"forming energy spheres",
		"touching floating runes",
		"communing with spirits pose",
		"dramatic pointing pose",
		"hands behind head carefree",
		"anime girl jump pose",
		"tsundere crossed arms",
		"v sign near face",
		"energetic hero stance",
		"perched like a harpy",
		"coiled serpent posture",
		"centaur ready stance",
		"angel wings spread wide",
		"demon crouched pose",
		"dragon tamer stance",
		"mermaid resting on rock",
		"golem kneeling guard pose",
		"faerie hovering pose"
	],
	"SETTINGS": [
		"ancient stone well",
		"old cutting room",
		"Edenic garden",
		"dim TV room",
		"abandoned hangar",
		"shadowed closet",
		"stellar gateway",
		"tiny cubby room",
		"public works hall",
		"shipping warehouse",
		"grand marble lobby",
		"crowded workroom",
		"old manor scullery",
		"castle guardroom",
		"collapsing card house",
		"private bathroom",
		"extraterrestrial ruin",
		"orbital landing deck",
		"quiet classroom",
		"dusty barroom",
		"monastic scriptorium",
		"derelict space object",
		"skyport airdock",
		"grass-covered mound",
		"imperial durbar hall",
		"medical sick berth",
		"honeycomb chamber",
		"steam-filled bath",
		"shoebox apartment",
		"circular rotunda",
		"restricted zone",
		"heliosphere edge",
		"heavenly belfry",
		"lookout station",
		"sunlit sewing room",
		"glass sunporch",
		"underground vault",
		"empty depth chamber",
		"dead star body",
		"white observation room",
		"chaotic trading floor",
		"foggy sitting room",
		"engine control room",
		"hanging cocoon nest",
		"marble colonnade",
		"storm shelter",
		"clean research room",
		"front reception room",
		"steel ship hull",
		"ancient masonry hall",
		"old manor mansion",
		"castle lodging room",
		"outer cosmos void",
		"arcaded walkway",
		"stone balcony",
		"coatroom foyer",
		"prison cell block",
		"corporate boardroom",
		"zodiac observatory",
		"waiting area hall",
		"vapour bath chamber",
		"hospital shower room",
		"quiet bedchamber",
		"paradise valley",
		"white vapor bath",
		"fountain courtyard",
		"sculpture gallery",
		"sports stadium",
		"ballroom hall",
		"television lounge",
		"planetary house",
		"recreation room",
		"urban solarium",
		"open hillside",
		"stone pillar hall",
		"hospital sickroom",
		"private den room",
		"grand monument",
		"old smoking room",
		"wooden dining room",
		"billiard parlor",
		"high stone arch",
		"cavern bowl chamber",
		"starship weapons platform",
		"deep universe layer",
		"solitary lookout tower",
		"hellish furnace room",
		"stone torture chamber",
		"astral observatory",
		"art museum gallery",
		"haunted locker room",
		"library reading room",
		"wind tunnel lab",
		"theatre dressing room",
		"old repair shed",
		"conference chamber",
		"council hall",
		"empty arena floor",
		"vast jungle gym",
		"towering obelisk",
		"library vestibule",
		"sunlit cloister",
		"castle great hall",
		"museum foyer",
		"studio workshop",
		"corporate office",
		"underground sewer",
		"ancient catacombs",
		"low grotto cave",
		"post apocalyptic wasteland",
		"cyberpunk alley",
		"steampunk workshop",
		"gothic fortress",
		"red gothic castle",
		"desert sun dunes",
		"frozen arctic plain",
		"deep jungle ruin",
		"haunted cemetery",
		"ancient mausoleum",
		"secret temple shrine",
		"abandoned laboratory",
		"industrial factory floor",
		"old brick warehouse",
		"film shooting set",
		"university library",
		"hospital emergency ward",
		"police station hall",
		"city hall atrium",
		"crowded street market",
		"train station platform",
		"airport departure hall",
		"orbital space station",
		"deep space void",
		"moon crater plain",
		"asteroid bunker",
		"alien ocean abyss",
		"underwater city ruins",
		"abandoned theme park",
		"amusement park midway",
		"creaking ghost town",
		"enchanted forest grove",
		"haunted mansion floor",
		"giants stone castle",
		"glacial ice cavern",
		"old lighthouse top",
		"luxury yacht deck",
		"magic castle hall",
		"military base bunker",
		"opera house stage",
		"oil rig platform",
		"spy headquarters",
		"subway station hall",
		"supermarket aisle",
		"swamp marshland",
		"tea house interior",
		"time travel lab",
		"treehouse platform",
		"venetian canal bridge",
		"viking longship deck",
		"vineyard hillside",
		"war battlefield trench",
		"wax museum hall",
		"wine cellar vault",
		"worlds fair pavilion",
		"castle made of stars",
		"sand waterfall cliffs",
		"black hole waterfall",
		"cosmic star ocean",
		"electric neon forest",
		"floating cloud city",
		"diamond mountain peak",
		"frozen volcano mouth",
		"floating life tree",
		"crystal palace hall",
		"city on a cloud",
		"candy island shore",
		"crystal city spires",
		"coral forest reef",
		"tree city canopy",
		"diamond cave interior",
		"sky flower garden",
		"underwater golden city",
		"volcanic city core",
		"comet surface city",
		"cloud forest canopy",
		"dream city skyline",
		"crystal mountain ridge",
		"island of dreams",
		"island of illusions",
		"city of illusions",
		"mirror hall chamber",
		"crystal sky bridge",
		"diamond sky vault",
		"island of the sun",
		"palace of the moon",
		"city of the stars",
		"island of the gods",
		"palace of the demons",
		"city of the angels",
		"dragon island cliffs",
		"mermaid city reef",
		"fairy forest glade",
		"giant kingdom walls",
		"goblin market den",
		"elven city canopy",
		"dwarven forge hall",
		"troll cave fortress",
		"unicorn meadow field",
		"golden mountain peak",
		"diamond planet surface",
		"stone flower fields",
		"neon light forest",
		"lake of fire shore",
		"cotton candy clouds",
		"rainbow sky bridge",
		"turtle back city",
		"floating book island",
		"orb forest meadow",
		"ice cream mountain",
		"crystal underground city",
		"lantern sky island",
		"floating rainbow tower",
		"glowing jellyfish sea",
		"crystal blossom city",
		"diamond tree grove",
		"giant mushroom island",
		"candy volcano crater",
		"mirror mountain peak",
		"ice sculpture city",
		"neon tree island",
		"palace of ice and fire",
		"crystal maze chamber",
		"glowing crystal cave",
		"upside down forest",
		"floating mist island",
		"floating rock mountain",
		"star ocean horizon",
		"bubble city sky",
		"upside down waterfall cliffs",
		"glowing mushroom forest",
		"floating cloud gardens",
		"diamond sand island",
		"floating bridge city",
		"floating lantern forest",
		"crystal snow mountain",
		"rainbow coral island",
		"floating crystal palace",
		"glowing coral ocean",
		"floating mountain city",
		"glowing stone island",
		"glowing tree mountain",
		"glowing plankton ocean",
		"floating light orb grove",
		"floating waterfall city",
		"crystal butterfly island",
		"floating stair mountain",
		"floating diamond palace",
		"glowing seaweed world",
		"floating palm island",
		"floating firefly forest",
		"floating stone city",
		"floating pyramid mountain",
		"glowing jellyfish ocean",
		"floating lotus island",
		"floating pearl palace",
		"glowing fish world",
		"floating fountain city",
		"crystal seashell island",
		"floating crystal mountain",
		"glowing life tree forest",
		"floating garden city",
		"floating castle island",
		"floating gold palace",
		"glowing starfish world",
		"floating water mountain",
		"glowing creature ocean",
		"floating lighthouse island",
		"floating sculpture city",
		"floating willow forest",
		"floating cloud mountain",
		"glowing whale ocean",
		"floating flower forest",
		"floating life tree island",
		"floating diamond gold palace",
		"glowing octopus world",
		"floating pyramid city",
		"floating star mountain",
		"glowing dolphin ocean"
	],
	"SCENE": [
		"afterlife haze",
		"wartime tension",
		"roman era",
		"ancient era",
		"prehistoric dawn",
		"harvest season",
		"turn of the century",
		"ephemeral moment",
		"judgment day sky",
		"Halloween night",
		"blue moon night",
		"spring morning",
		"summer heat",
		"autumn chill",
		"winter frost",
		"hard times mood",
		"calm atmosphere",
		"flooded world",
		"heavy fog",
		"dust devil spiral",
		"roaring gale",
		"solar halo sky",
		"windstream air",
		"gentle wave light",
		"morning light",
		"afternoon glow",
		"evening hush",
		"daybreak calm",
		"sunrise glow",
		"mid morning",
		"brunch time",
		"mid afternoon",
		"sunset glow",
		"twilight haze",
		"dusk horizon",
		"nighttime quiet",
		"midnight stillness",
		"witching hour",
		"early morning chill",
		"late morning warmth",
		"lunchtime light",
		"siesta heat",
		"cocktail hour",
		"golden hour",
		"blue hour",
		"magic hour",
		"red sky",
		"pink sky",
		"orange sky",
		"purple sky",
		"starry night",
		"moonlit night",
		"cloudy night",
		"clear night",
		"full moon night",
		"new moon night",
		"waxing moon",
		"waning moon",
		"harvest moon",
		"blood moon",
		"supermoon",
		"crescent moon",
		"gibbous moon",
		"meteor shower",
		"shooting stars",
		"northern lights",
		"southern lights",
		"first light",
		"last light",
		"crepuscular rays",
		"daytime heat",
		"late afternoon glow",
		"sundown horizon",
		"starlight glow",
		"firefly light",
		"torchlight shadow",
		"candlelight warmth",
		"neon light glow",
		"sunrise colors",
		"sunset colors",
		"rainbow hues",
		"sky blue tone",
		"cloudy gray tone",
		"hazy yellow light",
		"misty white air",
		"fiery red atmosphere",
		"deep purple dusk",
		"vibrant green glow",
		"cool blue light",
		"warm yellow glow",
		"moody gray tone",
		"soft pink sky",
		"pale blue haze",
		"deep navy night",
		"bright white light",
		"pitch black void",
		"gray twilight",
		"glowing embers",
		"bright skies",
		"pale clouds",
		"dark shadows",
		"soft shadows",
		"silhouette light",
		"low light mood",
		"pink horizon",
		"orange dawn",
		"red dawn",
		"gray dawn",
		"bright morning",
		"early afternoon glow",
		"evening breeze",
		"cool night air",
		"warm night sky",
		"sunny day",
		"cloudy day",
		"rainy day",
		"foggy morning",
		"misty evening",
		"stormy night",
		"thunderstorm sky",
		"lightning streaks",
		"sunny afternoon",
		"rainbow after rain",
		"soft light mood",
		"harsh light mood",
		"darkening sky",
		"changing light",
		"fireworks night",
		"serene sunset",
		"deep blue night",
		"warm sunset",
		"cold sunset",
		"bright sunrise",
		"cloudy sunrise",
		"foggy sunrise",
		"misty sunrise",
		"crisp morning",
		"snowy morning",
		"frosty morning",
		"icy morning",
		"overcast morning",
		"peaceful morning",
		"quiet night",
		"peaceful evening",
		"gloaming light",
		"moonrise night",
		"moonset horizon",
		"dawn chorus",
		"evening light",
		"morning light",
		"twilight glow",
		"purple dawn",
		"purple dusk",
		"deep blue evening",
		"pastel sky",
		"stormy afternoon",
		"gloomy day",

		"full moon night",
		"waning gibbous moon",
		"waxing crescent moon",

		"orbital sunrise",
		"orbital sunset",
		"midnight sun",
		"polar night",
		"summer solstice",
		"winter solstice",
		"equinox light",

		"sunrise over mountains",
		"night sky with stars",
		"northern lights night",
		"fireflies at night",
		"sunny sky with clouds",
		"overcast sky",
		"rainy evening",
		"misty lake morning",
		"late sunset",
		"hazy sky",
		"heat lightning",
		"damp morning",
		"fresh morning",
		"thunderstorm at dusk",
		"blizzard at dawn",
		"raining gold",
		"raining diamonds",
		"raining red paint",
		"snowing stones",
		"diamond hail",
		"rainbow hurricane",
		"rainbow tornado",
		"flame tornado",
		"lightning storm at midnight",
		"foggy afternoon",
		"misty night",
		"clear morning",
		"hazy evening",
		"snowstorm at night",
		"heatwave at noon",
		"misty twilight",
		"icy night",
		"frosty evening",
		"sunny day with rainbow",
		"morning with rainbows",
		"night sky with auroras",
		"sunset with lightning",
		"rainbow lightning storm",
		"thunderstorm at noon",
		"snowstorm at sunset",
		"evening meteor shower",
		"foggy morning with rainbows",
		"thunderstorm with hail",
		"hailstorm night",
		"sandstorm at dawn",
		"rainbow snowfall",
		"rainbow hailstorm",
		"rainbow mist",
		"sunset with pink lightning",
		"hurricane at dawn",
		"hurricane at sunset",
		"sunny day with hurricane",
		"sunny day with tornado",
		"evening fireflies",
		"thunderstorm with fireflies",
		"rainy morning with rainbows",
		"clear day with auroras",
		"aurora storm night"
	],
	"SURREAL SCENE": [
		"dream logic dawn",
		"world made of echoes",
		"gravity folding inward",
		"time melting sideways",
		"endless horizon loop",
		"sky opening like paper",
		"ocean suspended above",
		"forest whispering names",
		"shadows walking alone",
		"light behaving strangely",
		"air trembling with memory",
		"rain falling upward",
		"sunrise without a sun",
		"night with no darkness",
		"color bleeding from sky",
		"frozen lightning moment",
		"moon cracked open",
		"stars drifting slowly downward",
		"echoes brighter than light",
		"fractured daydream",
		"endless hallway mirage",
		"dusk made of static",
		"sun humming softly",
		"midnight blooming flowers",
		"horizon bending upward",
		"memories raining gently",
		"silence thick as fog",
		"mirrors blooming like trees",
		"sound rippling across air",
		"footsteps with no walker",
		"wind speaking in voices",
		"clouds shaped like thoughts",
		"shimmering unreality",
		"broken reflections floating",
		"gravity free twilight",
		"astral bloom horizon",
		"dream stitched morning",
		"sky dripping gold",
		"shadows glowing faintly",
		"moon made of smoke",
		"time spiraling outward",
		"reality flickering softly",
		"stars raining like seeds",
		"light with no source",
		"endless corridor glow",
		"sleepwalking horizon",
		"day and night overlapping",
		"sunset carved from glass",
		"dawn bending like fabric",
		"air full of forgotten whispers",
		"midnight blooming wings",
		"color shifting fog",
		"horizon breathing slowly",
		"sky shimmering like water",
		"phantom auroras",
		"floating constellations",
		"memory storm",
		"echo storm sky",
		"submerged starlight",
		"crystalline dusk",
		"whispering aurora",
		"shadow tide",
		"illuminated void",
		"impossible sunrise",
		"sunken daylight",
		"folding moonlight",
		"fractured twilight",
		"soft neon dawn",
		"glowing shadow rain",
		"mirror horizon",
		"drifting starlit mist",
		"light raining like petals",
		"sky pulsing gently",
		"timeless night",
		"shattered daylight",
		"glimmering alternate dawn",
		"breathing starlight",
		"glitching morning light",
		"dream dust storm",
		"weightless moonrise",
		"soft glitch dusk",
		"velvet horizon",
		"astral tide",
		"whisper dusk",
		"fog speaking truths",
		"burning cold atmosphere",
		"melting moon horizon",
		"dream stitched twilight",
		"ghost light sunrise",
		"creaking sky vault",
		"endless looping noon",
		"shifting silhouette day",
		"shadow soaked dusk",
		"midnight glow tide",
		"horizon echo bloom",
		"star drenched air",
		"quiet impossible dawn",
		"moonglass night",
		"glowing snowfall of ash",
		"time fractured glow",
		"void shimmering gently",
		"light drifting like snow",
		"shadow bloom sunrise",
		"sky swallowing itself",
		"horizon made of dreams",
		"moonlight dripping slowly",
		"stars breaking like waves",
		"gravity drifting away",
		"colorless rainbow moment",
		"neon fog horizon",
		"sunlight dissolving",
		"memory saturated dusk",
		"constant twilight",
		"deep void shimmer",
		"dreamlike blue hush",
		"eternal morning glow",
		"empty starlit silence",
		"low gravity sunrise",
		"whispering cosmic wind",
		"starlight bleeding downward",
		"blurred reality dawn",
		"gentle cosmic rupture",
		"phantom morning",
		"phantom dusk",
		"moon shimmer veil"
	],
	"ARTISTS": [
		"Artstation",
		"by Agnes Lawrence Pelton",
		"by Akihito Yoshida",
		"by Alex Grey",
		"by Alexander Jansson",
		"by Alphonse Mucha",
		"by Andy Warhol",
		"by Artgerm",
		"by Asaf Hanuka",
		"by Aubrey Beardsley",
		"by Banksy",
		"by Beeple",
		"by Ben Enwonwu",
		"by Bob Eggleton",
		"by Caravaggio Michelangelo Merisi",
		"by Caspar David Friedrich",
		"by Chris Foss",
		"by Claude Monet",
		"by Dan Mumford",
		"by David Mann",
		"by Diego Velázquez",
		"by Disney Animation Studios",
		"by Édouard Manet",
		"by Esao Andrews",
		"by Frida Kahlo",
		"by Gediminas Pranckevicius",
		"by Georgia O'Keeffe",
		"by Greg Rutkowski",
		"by Gustave Doré",
		"by Gustave Klimt",
		"by H.R. Giger",
		"by Hayao Miyazaki",
		"by Henri Matisse",
		"by HP Lovecraft",
		"by Ivan Shishkin",
		"by Jack Kirby",
		"by Jackson Pollock",
		"by James Jean",
		"by Jim Burns",
		"by Johannes Vermeer",
		"by John William Waterhouse",
		"by Katsushika Hokusai",
		"by Kim Tschang Yeul",
		"by Ko Young Hoon",
		"by Leonardo da Vinci",
		"by Lisa Frank",
		"by M.C Escher",
		"by Mahmoud Saïd",
		"by Makoto Shinkai",
		"by Marc Simonetti",
		"by Mark Brooks",
		"by Michelangelo",
		"by Pablo Picasso",
		"by Paul Klee",
		"by Peter Mohrbacher",
		"by Pierre-Auguste Renoir",
		"by Pixar Animation Studios",
		"by Rembrandt",
		"by Richard Dadd",
		"by Rossdraws",
		"by Salvador Dalí",
		"by Sam does Arts",
		"by Sandro Botticelli",
		"by Ted Nasmith",
		"by Ten Hundred",
		"by Thomas Kinkade",
		"by Tivadar Csontváry Kosztka",
		"by Victo Ngai",
		"by Vincent di Fate",
		"by Vincent van Gogh",
		"by Wes Anderson",
		"by wlop",
		"by Yoshitaka Amano",
		"by Edgar Degas",
		"by Francis Bacon",
		"by Piet Mondrian",
		"by Rene Magritte",
		"by Mary Cassatt",
		"by Edward Hopper",
		"by Keith Harring",
		"by Jean-Michel Basquiat",
		"by Yayoi Kusama",
		"by Grant Wood",
		"by Artemisia Gentileschi",
		"by Edvard Munch",
		"by Egon Schiele",
		"by Wassily Kandinsky",
		"by Henri Cartier-Bresson",
		"by Norman Rockwell",
		"by James Abbott McNeill Whistler",
		"by Man Ray",
		"by Felix Nadar",
		"by Dorothea Lange",
		"by Annie Leibovitz",
		"by Richard Avedon",
		"by Helmut Newton"
	],
	"CGI RENDERINGS": [
		"3D Render",
		"Corona Render",
		"Creature Design",
		"Cycles Render",
		"Detailed Render",
		"Environment Design",
		"Intricate Environment",
		"LSD Render",
		"Octane Render",
		"PBR",
		"Glass Caustics",
		"Global Illumination",
		"Subsurface Scattering"
	],
	"CGI SOFTWARES": [
		"3D Model",
		"3D Sculpt",
		"3Ds Max Model",
		"Blender Model",
		"Cinema4d Model",
		"Maya Model",
		"Unreal Engine",
		"Zbrush Sculpt"
	],
	"CAMERAS": [
		"Aerial View",
		"Canon50",
		"Cinematic",
		"Close-up",
		"Color Grading",
		"Dramatic", "Film Grain",
		"Fisheye Lens",
		"Glamor Shot", "Glow Lighting",
		"Golden Hour",
		"Hyperfocal Distance",
		"Low Light",
		"Macro",
		"Macro Lens",
		"Macro Photography",
		"Macro Shot",
		"Medium Shot",
		"Night Photography",
		"Night Vision",
		"Panorama",
		"Realistic",
		"Telephoto",
		"Ultra Wide",
		"Wide Angle",
		"Zoom",
		"HD",
		"Landscape",
		"Lens Flare",
		"Macro",
		"Polaroid",
		"Photoshoot",
		"Portrait",
		"Studio Lighting",
		"Vintage",
		"War Photography",
		"White Balance",
		"Wildlife Photography"
	],
	"CARVINGS AND ETCHINGS": [
		"etching",
		"Linocut",
		"Paper Model",
		"Paper-Mache",
		"Papercutting",
		"Pyrography",
		"Wood-Carving"
	],
	"COLORS": [
		"Beautiful Lighting",
		"Cold Color Palette",
		"Colorful",
		"Dynamic Lighting",
		"Electric Colors",
		"Infrared",
		"Pastel",
		"Neon",
		"Synthwave",
		"Warm Color Palette"
	],
	"DRAWING STYLES": [
		"Cel Shading",
		"Children's Drawing",
		"Crosshatch",
		"Detailed and Intricate",
		"Doodle",
		"Dot Art",
		"Line Art",
		"Sketch"
	],
	"EMOTIONS": [
		"Angry",
		"Bitter",
		"Disgusted",
		"Embarrassed",
		"Evil",
		"Excited",
		"Fear",
		"Funny",
		"Happy",
		"Horrifying",
		"Lonely",
		"Sad", "Serene",
		"Surprised",
		"Melancholic"
	],
	"PENS": [
		"Chalk",
		"Colored Pencil",
		"Graphite",
		"Ink",
		"Oil Paint",
		"Pastel Art"
	],
	"VISUAL STYLES": [
		"2D",
		"8-Bit",
		"16-Bit",
		"Anaglyph",
		"Anime",
		"Art Nouveau",
		"Bauhaus",
		"Baroque",
		"CGI",
		"Cartoon",
		"Comic Book",
		"Concept Art",
		"Constructivist",
		"Cubist",
		"Digital Art",
		"Dadaist",
		"Expressionist",
		"Fantasy",
		"Fauvist",
		"Figurative",
		"Graphic Novel",
		"Geometric",
		"Hard Edge Painting",
		"Hydrodipped",
		"Impressionistic",
		"Lithography",
		"Manga",
		"Minimalist",
		"Modern Art",
		"Mosaic",
		"Mural",
		"Naive",
		"Neoclassical",
		"Photo",
		"Realistic",
		"Rococo",
		"Romantic",
		"Street Art",
		"Symbolist",
		"Stuckist",
		"Surrealist",
		"Visual Novel",
		"Watercolor"
	],
	"FORMAT": [
		"classical oil painting",
		"renaissance fresco",
		"baroque painting",
		"romanticism painting",
		"neoclassical painting",
		"symbolist painting",
		"mythological painting",
		"pre-raphaelite painting",
		"impressionist painting",
		"post-impressionist painting",
		"expressionist painting",
		"surrealist painting",
		"fantasy illustration",
		"gothic illustration",
		"mythic tapestry",
		"religious icon painting",
		"ink and wash painting",
		"sumi-e ink painting",
		"medieval illuminated manuscript",
		"charcoal drawing",
		"graphite sketch",
		"colored pencil sketch",
		"pen and ink illustration",
		"pastel drawing",
		"chalk mural",
		"tempera painting",
		"encaustic wax painting",
		"woodblock print",
		"lithograph print",
		"etching plate illustration",
		"marble sculpture",
		"bronze sculpture",
		"stone relief carving",
		"clay figurine",
		"ceramic statue",
		"wood carving",
		"jade carving",
		"glass sculpture",
		"ice sculpture",
		"sand sculpture",
		"paper craft model",
		"origami figure",
		"metal welded sculpture",
		"digital painting",
		"vector illustration",
		"graphic novel panel",
		"comic book panel",
		"concept art sheet",
		"storyboard frame",
		"matte painting",
		"artbook plate",
		"poster graphic",
		"lineart illustration",
		"cel-shaded animation frame",
		"watercolor illustration",
		"mixed media collage",
		"glitch art composition",
		"vaporwave graphic",
		"pixel art sprite",
		"low-poly render",
		"high-poly 3d render",
		"claymation frame",
		"stop motion still",
		"studio photography",
		"film photography",
		"medium format film photo",
		"black and white film photo",
		"color film photo",
		"sepia toned photograph",
		"macro photography",
		"portrait photography",
		"fashion photography",
		"editorial photography",
		"beauty close-up",
		"hyperrealistic photograph",
		"cinematic still frame",
		"anamorphic widescreen still",
		"telephoto lens shot",
		"wide angle shot",
		"fisheye lens shot",
		"tilt shift miniature shot",
		"red camera 4k still",
		"35mm film still",
		"70mm film still",
		"polaroid photo",
		"instant film shot",
		"disposable camera photo",
		"2000s digital camera photo",
		"camcorder still frame",
		"vhs still frame",
		"crt screen photograph",
		"cctv security footage",
		"thermal imaging shot",
		"infrared photography",
		"night vision footage",
		"drone photography",
		"underwater photography",
		"x-ray image",
		"microscope photography",
		"magazine cover",
		"teen magazine cover",
		"fashion magazine cover",
		"movie magazine cover",
		"tabloid newspaper cover",
		"newspaper illustration",
		"broadsheet print",
		"pamphlet illustration",
		"book cover",
		"fantasy novel cover",
		"science fiction paperback cover",
		"vinyl album cover",
		"concert poster",
		"movie poster",
		"film poster",
		"theatrical playbill",
		"propaganda poster",
		"travel postcard",
		"police sketch",
		"courtroom sketch",
		"architectural blueprint",
		"technical schematic drawing",
		"film still",
		"silent film frame",
		"noir film frame",
		"grindhouse film still",
		"vhs horror still",
		"retro anime screenshot",
		"modern anime keyframe",
		"tv broadcast still",
		"news broadcast frame",
		"reality tv screenshot",
		"found footage still",
		"bodycam footage",
		"dashcam footage",
		"helmet cam footage",
		"home video still",
		"holographic display",
		"augmented reality overlay",
		"virtual reality viewport",
		"game screenshot",
		"pixelated retro game screenshot",
		"hud display frame",
		"terminal green text screen",
		"error glitch frame",
		"security ui interface",
		"digital scan artifact",
		"engraved metal plate",
		"glass plate photograph",
		"daguerreotype photo",
		"cyanotype print",
		"blueprint style render",
		"neon line render",
		"wireframe render",
		"clay bust study",
		"wax figurine render",
		"laser etching",
		"burned wood pyrography",
		"stitched textile artwork",
		"quilt illustration panel",
		"dreamlike painterly blur",
		"cosmic nebula style",
		"hyperreal dream photograph",
		"misty ethereal painting",
		"fractured mirror format",
		"dripping paint surrealism",
		"collapsing geometry art",
		"infinite recursion frame",
		"floating frame-in-frame image",
		"parallel universe photo",
		"liminal analog film frame",
		"time distortion photograph",
		"light trail long exposure",
		"bokeh heavy portrait",
		"starfield composite",
		"shadow silhouette study",
		"shitty smartphone photo",
		"overexposed flash photo",
		"blurry motion shot",
		"accidental pocket photo",
		"bad disposable camera shot",
		"grandma’s living room photo",
		"mall photo booth picture",
		"roller rink posed snapshot",
		"yearbook portrait",
		"school portrait backdrop",
		"old webcam shot",
		"360p internet screenshot",
		"pixelated flip phone photo",
		"imax film still",
		"epic widescreen panorama",
		"dramatic chiaroscuro portrait",
		"heroic golden hour photo",
		"high contrast action freeze frame",
		"overhead drone cinematic shot",
		"dark fantasy illustration",
		"epic sci fi keyframe",
		"mythological fresco style"
	],
	"PROMPT TEMPLATES": [
		"A [SUBJECTS], wearing [CLOTHING], with [PROPS], in a beautiful [SETTINGS], [SCENE]",
		"A [SUBJECTS] wearing [CLOTHING] in a [SETTINGS], captured in [FORMAT].",
		"A [FEMALE SUBJECTS] in [CLOTHING STYLES] clothing, holding [PROPS], striking a [POSES] pose in a vivid [SCENE].",
		"A [SUBJECTS] with [PROPS] inside a beautiful [SETTINGS], illustrated in a [VISUAL STYLES] style.",
		"A [FEMALE SUBJECTS] wearing [CLOTHING] and posing in [POSES] within a surreal [SURREAL SCENE].",
		"A [SUBJECTS] standing in a dramatic [SCENE], dressed in [CLOTHING STYLES] fashion, rendered as a [FORMAT].",
		"A [FEMALE SUBJECTS] carrying [PROPS] in a mystical [SETTINGS], portrayed through [VISUAL STYLES].",
		"A [SUBJECTS] in [CLOTHING], performing a dynamic [POSES] pose inside a [SCENE], captured in [FORMAT].",
		"A [FEMALE SUBJECTS] surrounded by [PROPS] in a dreamlike [SURREAL SCENE], depicted in [VISUAL STYLES].",
		"A [SUBJECTS] wearing [CLOTHING], standing in a luminous [SETTINGS], rendered as a detailed [FORMAT].",
		"A [FEMALE SUBJECTS] in [CLOTHING STYLES] attire, posing in [POSES] within a serene [SCENE].",
		"A [SUBJECTS] interacting with [PROPS] in an atmospheric [SETTINGS], created in [VISUAL STYLES].",
		"A [FEMALE SUBJECTS] in [CLOTHING], drifting through a surreal [SURREAL SCENE], shaped in [FORMAT].",
		"A [SUBJECTS] striking a [POSES] pose inside a dramatic [SCENE], wearing [CLOTHING STYLES] elements.",
		"A [FEMALE SUBJECTS] holding [PROPS] in a symbolic [SETTINGS], expressed in a [VISUAL STYLES] aesthetic.",
		"A [SUBJECTS] in [CLOTHING] and [POSES], wandering through a shifting [SURREAL SCENE] in [FORMAT].",
		"A [FEMALE SUBJECTS] wearing [CLOTHING] in a vivid [SCENE], rendered as a [CGI RENDERINGS] using [CGI SOFTWARES].",
		"A [SUBJECTS] holding [PROPS] in a striking [SETTINGS], illustrated in [DRAWING STYLES] with [PENS].",
		"A [FEMALE SUBJECTS] posing in [POSES] amid a glowing [SURREAL SCENE], depicted in [COLORS] tones using [FORMAT].",
		"A [SUBJECTS] in [CLOTHING STYLES] fashion, captured through a [CAMERAS] lens inside a dramatic [SCENE].",
		"A [FEMALE SUBJECTS] surrounded by [PROPS] inside a mystical [SETTINGS], carved in [CARVINGS AND ETCHINGS] style.",
		"A [SUBJECTS] expressing [EMOTIONS], wearing [CLOTHING], standing in a cinematic [SCENE] as a [FORMAT].",
		"A [FEMALE SUBJECTS] in [CLOTHING], performing [POSES] inside a surreal [SURREAL SCENE], created using [VISUAL STYLES].",
		"A [SUBJECTS] holding [PROPS] within a moody [SETTINGS], rendered as a [CGI RENDERINGS] with [CGI SOFTWARES].",
		"A [FEMALE SUBJECTS] in bright [COLORS], photographed with [CAMERAS] in a dramatic [SCENE].",
		"A [SUBJECTS] dressed in [CLOTHING STYLES], striking a [POSES] pose in a glowing [SURREAL SCENE], expressed in [FORMAT].",
		"A [FEMALE SUBJECTS] carrying [PROPS], standing in a lush [SETTINGS], illustrated using [DRAWING STYLES] and [PENS].",
		"A [SUBJECTS] in [CLOTHING], captured by [CAMERAS] within an ethereal [SCENE], finished in [VISUAL STYLES].",
		"A [FEMALE SUBJECTS] expressing [EMOTIONS], framed in a painterly [FORMAT], set inside a mysterious [SETTINGS].",
		"A [SUBJECTS] with [PROPS] in a cosmic [SURREAL SCENE], shaped through [CGI SOFTWARES] as a [CGI RENDERINGS].",
		"A [FEMALE SUBJECTS] wearing [CLOTHING], performing [POSES] in a radiant [SCENE], colored in [COLORS] and rendered in [FORMAT]."
	]
};
